package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/brightsidedeveloper/go-gql-pgx/graph/model"
)

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*model.Viewer, error) {
	return &model.Viewer{}, nil
}

// Users is the resolver for the users field.
func (r *viewerResolver) Users(ctx context.Context, obj *model.Viewer) ([]*model.User, error) {
	return []*model.User{
		{
			ID:   "1",
			Name: "John Doe",
		},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Viewer returns ViewerResolver implementation.
func (r *Resolver) Viewer() ViewerResolver { return &viewerResolver{r} }

type queryResolver struct{ *Resolver }
type viewerResolver struct{ *Resolver }
