// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Viewer struct {
	Users []*User `json:"users"`
}
